# Generated by Django 5.1.15 on 2026-02-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("determinato", "Determinato"), ("indeterminato", "Indeterminato"), ("stagista", "Stagista")],
                        max_length=50,
                    ),
                ),
                (
                    "ccnl",
                    models.CharField(
                        choices=[("metalmeccanico", "Metalmeccanico"), ("commercio", "Commercio")], max_length=50
                    ),
                ),
                ("ral", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contracts", to="employees.employee"
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "-start_date"],
            },
        ),
    ]
