# Generated by Django 5.1.15 on 2026-02-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="contracts/%Y/%m/"),
        ),
    ]
